//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMS.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZEMS.Application.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string LabelActivate {
            get {
                return ResourceManager.GetString("LabelActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string LabelActivated {
            get {
                return ResourceManager.GetString("LabelActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate User.
        /// </summary>
        public static string LabelActivateUser {
            get {
                return ResourceManager.GetString("LabelActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string LabelAdd {
            get {
                return ResourceManager.GetString("LabelAdd", resourceCulture);
            }
        }        
             
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LabelBack {
            get {
                return ResourceManager.GetString("LabelBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string LabelBackToList {
            get {
                return ResourceManager.GetString("LabelBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LabelClose {
            get {
                return ResourceManager.GetString("LabelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string LabelCode {
            get {
                return ResourceManager.GetString("LabelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string LabelDeactivate {
            get {
                return ResourceManager.GetString("LabelDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate User.
        /// </summary>
        public static string LabelDeactivateUser {
            get {
                return ResourceManager.GetString("LabelDeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }     
             
        /// <summary>
        ///   Looks up a localized string similar to User Detail.
        /// </summary>
        public static string LabelDetailsUser {
            get {
                return ResourceManager.GetString("LabelDetailsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
                      
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string LabelEditUser {
            get {
                return ResourceManager.GetString("LabelEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string LabelFullName {
            get {
                return ResourceManager.GetString("LabelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LabelHome {
            get {
                return ResourceManager.GetString("LabelHome", resourceCulture);
            }
        }
                    
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string LabelPrivacy {
            get {
                return ResourceManager.GetString("LabelPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string LabelRemove {
            get {
                return ResourceManager.GetString("LabelRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string LabelRoleName {
            get {
                return ResourceManager.GetString("LabelRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string LabelRoles {
            get {
                return ResourceManager.GetString("LabelRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Selection.
        /// </summary>
        public static string LabelRolesSelection {
            get {
                return ResourceManager.GetString("LabelRolesSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string LabelUserList {
            get {
                return ResourceManager.GetString("LabelUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string LabelUserRole {
            get {
                return ResourceManager.GetString("LabelUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string LabelUsers {
            get {
                return ResourceManager.GetString("LabelUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string LabelView {
            get {
                return ResourceManager.GetString("LabelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured. MethodName: {MethodName}, Parameter: {Parameter}.
        /// </summary>
        public static string MessagePatternErrorLog {
            get {
                return ResourceManager.GetString("MessagePatternErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation successful.
        /// </summary>
        public static string PromptMessageActivateSuccess {
            get {
                return ResourceManager.GetString("PromptMessageActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to activate this user?.
        /// </summary>
        public static string PromptMessageActivateUserConfirmation {
            get {
                return ResourceManager.GetString("PromptMessageActivateUserConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation successful.
        /// </summary>
        public static string PromptMessageDeactivateSuccess {
            get {
                return ResourceManager.GetString("PromptMessageDeactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deactivate this user?.
        /// </summary>
        public static string PromptMessageDeactivateUserConfirmation {
            get {
                return ResourceManager.GetString("PromptMessageDeactivateUserConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured, please contact your system administrator.
        /// </summary>
        public static string PromptMessageDefaultError {
            get {
                return ResourceManager.GetString("PromptMessageDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string PromptMessageDeleteConfirmation {
            get {
                return ResourceManager.GetString("PromptMessageDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete success.
        /// </summary>
        public static string PromptMessageDeleteSuccess {
            get {
                return ResourceManager.GetString("PromptMessageDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string PromptMessageFieldIsRequired {
            get {
                return ResourceManager.GetString("PromptMessageFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save?.
        /// </summary>
        public static string PromptMessageSaveConfirmation {
            get {
                return ResourceManager.GetString("PromptMessageSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save success.
        /// </summary>
        public static string PromptMessageSaveSuccess {
            get {
                return ResourceManager.GetString("PromptMessageSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update success.
        /// </summary>
        public static string PromptMessageUpdateSuccess {
            get {
                return ResourceManager.GetString("PromptMessageUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update this user&apos;s information?.
        /// </summary>
        public static string PromptMessageUpdateUserConfirmation {
            get {
                return ResourceManager.GetString("PromptMessageUpdateUserConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this feature..
        /// </summary>
        public static string PromptUnAuthorized {
            get {
                return ResourceManager.GetString("PromptUnAuthorized", resourceCulture);
            }
        }
		
		
        /// <summary>
        /// Looks up a localized string similar to Add Employee
        /// </summary>
        public static string LabelAddEmployee {
            get {
                return ResourceManager.GetString("LabelAddEmployee", resourceCulture);
            }
        }
        /// <summary>
        /// Looks up a localized string similar to Edit Employee
        /// </summary>
        public static string LabelEditEmployee {
            get {
                return ResourceManager.GetString("LabelEditEmployee", resourceCulture);
            }
        }
        /// <summary>
        /// Looks up a localized string similar to Delete Employee
        /// </summary>
        public static string LabelDeleteEmployee {
            get {
                return ResourceManager.GetString("LabelDeleteEmployee", resourceCulture);
            }
        }
        /// <summary>
        /// Looks up a localized string similar to Employee Details
        /// </summary>
        public static string LabelDetailsEmployee {
            get {
                return ResourceManager.GetString("LabelDetailsEmployee", resourceCulture);
            }
        }
        /// <summary>
        /// Looks up a localized string similar to Employee List
        /// </summary>
        public static string LabelEmployeeList {
            get {
                return ResourceManager.GetString("LabelEmployeeList", resourceCulture);
            }
        }
        /// <summary>
        /// Looks up a localized string similar to Employee
        /// </summary>
        public static string LabelEmployee {
            get {
                return ResourceManager.GetString("LabelEmployee", resourceCulture);
            }
        }

    }
}
